### PR TITLE
[WIP] Travis CI

### PR DESCRIPTION
**Pull request by johnthagen**
Work in progress to get Travis CI to correctly run all scapy3k tests.

### CODE REVIEW

**Comment by johnthagen** [comment]
@phaethon Could you advise about what the `script` section for the tests should be? This is running inside a Linux container.  Is there a better way to test this? I'm not familiar with the testing that scapy3k uses.

```
failed 78266D0A Sending and receiving an ICMP
failed 328290AA DNS request
failed 4ADCA21E TCP DNS request
passed 68FE0D72 Implicit logic
failed BCFA75B3 Port scan
failed 97755875 Traceroute function
failed 4A3C3B08 Result manipulation
failed 124ACC91 DNS packet manipulation
failed 70C79069 Arping
```

**Comment by phaethon** [comment]
Are these tests run with root privileges? It is required for some of the tests.

**Comment by johnthagen** [comment]
It is possible to use a `sudo` environment if required: https://docs.travis-ci.com/user/ci-environment/#Virtualization-environments

**Comment by johnthagen** [comment]
@phaethon `sudo` is enabled, but I'm not sure how the Travis build is interacting with the test script. I've only ever done `pytest` or straight `unittest` unit tests before for Python in Travis rather than custom shell scripts.

The current error is:

```bash
$ sudo ./run_tests
ERROR: cannot import [scapy]: No module named ipaddress
```

**Comment by phaethon** [comment]
As ipaddress is standard library module (https://docs.python.org/3/library/ipaddress.html) I am confused about this error. run_tests is a very simple bash script just running UTscapy.py, which is custom built test suite (used just for scapy afaik). You can open it and see yourself. Alternatively, you can call UTscapy.py directly with the correct interpreter.

**Comment by johnthagen** [comment]
I'm also confused about what is going 😕 . Not sure what else to try.

**Comment by phaethon** [comment]
Seems I have to make a more detailed look at this, but it will likely not be sooner than a week. You can, also, look at secdev/scapy repository and see how they implemented travis integration. ipaddress module was not used in secdev/scapy, but test suite itself is the same.

**Comment by tpltnt** [comment]
Is there any progress with with PR?

**Comment by phaethon** [comment]
Not yet. It is still on my list.

**Comment by phaethon** [comment]
I started looking into the issue and found out that some of the test cases need to be fixed, which I did. Now all regression.uts run successfully on my linux machine IF there is IPv6 configured and it is run as root. As a next step I will look into Travis script.

**Comment by johnthagen** [comment]
@phaethon Has this been merged already? https://github.com/phaethon/scapy/blob/master/.travis.yml

**Comment by johnthagen** [comment]
And are the tests actually running? https://travis-ci.org/phaethon/scapy/jobs/270887890

**Comment by phaethon** [comment]
No, it was not merged. Now it is. Tests are not automatically running, I will look into this.

**Pull request merged**
