### PR TITLE
Fix LLMNR decoder to work on the raw bytes rather than string->bytes …

### PR DESCRIPTION
**Pull request by richard-kinder**
Apologies if I mess this up - first time trying to use github.

Fix is for the LLMNR decoder to use the raw bytes value. Looks to me like a hangover from the Python2 port of scapy.

### CODE REVIEW

**Comment by phaethon** [comment]
Change seems good. Can you supply, also, an addition into the test suite (regression.uts)?

**Comment by richard-kinder** [comment]
I've added a simple test, not sure how it got added to the pull request, but here is is. Let me know if you want the test elsewhere in the file.

**Comment by richard-kinder** [comment]
Eriks, anything else I need to do to get this approved? Please let me know.

**Comment by phaethon** [comment]
It is enough. Good job! Committing.

**Pull request merged**
