### PR TITLE
Added PPPoED and LCP payloads

### PR DESCRIPTION
**Pull request by 0x5e**
[pppoe.pcap.zip](https://github.com/phaethon/scapy/files/121179/pppoe.pcap.zip)

### CODE REVIEW

**Comment by phaethon** [comment]
Commit seems good, but could you add some tests to the test suite for the new classes?

**Comment by 0x5e** [comment]
@phaethon ok, give me some time to learn :-)

**Comment by 0x5e** [comment]
update unit test

**Comment by phaethon** [comment]
Nice!

**Pull request merged**
