### PR TITLE
Ci windows tests

### PR DESCRIPTION
**Pull request by Bioh4z4rd**
Created a first sample for CI Tests using appveyor.

For the windows specific stuff iam only executing the new windows.uts file.
It can be extended to support the regression.uts in the future (once it is working flawlessly on windows)

### CODE REVIEW

**Comment by phaethon** [comment]
Thanks @Bioh4z4rd ! Anything I must change in appveyor or Github settings manually? Which tests are preventing regression.uts being used?

**Comment by phaethon** [comment]
I received first PR since appveyor code merging. And it gives "The specified module could not be found" error for the 64bit job. Can you look into this? Thanks in advance.

**Comment by Bioh4z4rd** [comment]
I reviewed what went wrong and it seems that chocolatey timed out while
trying to download the winpcap installation files. This results in import
errors later on. Retried it with my account and it was working. Can you
restart the build manually for the PR?

Eriks Dobelis <notifications@github.com> schrieb am Sa., 19. Aug. 2017 um
06:50 Uhr:

**Comment by Bioh4z4rd** [comment]
@phaethon 
I missed to answer your first question regarding the regression.uts on Windows.
I currently do not have my Windows machine available to cross check but some of the regression tests failed. Finally it started hanging for hours in the "automaton tests".
This happened for me in a locally installed Windows 7 instance as well as in a Virtual Machine running Windows 10.

Best regards,
Bioh4z4rd

**Pull request merged**
