### PR TITLE
Updated packet.py - Fixed packet dumping for both PDF and EPS output.

### PR DESCRIPTION
**Pull request by rwhalb**
Fixed functions pdfdump() and psdump() so that they now produce right side line drawing references to their corresponding hex components within the packet.

### CODE REVIEW

**Comment by phaethon** [comment]
Thanks for the patch. I have merged the request.

**Comment by rwhalb** [comment]
Eriks:

 

Created another pull that updates the docs. Removed the untested comment for
both pdfdump() and psdump().

 

BTW: I am the co-author of NST (Network Security Toolkit -
http://www.networksecuritytoolkit.org) and will be creating some
browser-based scapy integration.

 

I have now created an rpm: "scapy3k-3.0.0-105.nst22.noarch.rpm" that works
with NST 22-7334. Thank you for your contribution. The python3 port and
reading of pcapng files is fantastic!

 

---Thanks

 

Ron Henderson

**Comment by phaethon** [comment]
It is good to know that pdfdump and psdump are working. Thanks for reporting.
Did I understand correctly that scapy3k will be included in NST? Also, I have some other ideas (possibly outside the scope of scapy) on other network security related tools. How should I give you a notice for possible inclusion in NST if the ideas materialize into usable code?

**Comment by rwhalb** [comment]
Eriks:

 

Yes, scapy3k will be replacing scapy on NST. First it will be pushed out to
the NST Pro site repository: http://www.networksecuritytoolkit.org/nstpro/ 

 

Then when we do a new release for the public it will be included in that ISO
(Roughly Spring: 2016). Please correspond to me using this email address for
any new tools. I will be glad to include.

 

Since you are a contributor to NST now I will be glad to give you a NST Pro
subscription license so that you can stay current with NST. Let me know.

 

---Ron Henderson

**Pull request merged**
