### PR TITLE
layers.dhcpv6: fix relay handling

### PR DESCRIPTION
**Pull request by flokli**
Relay Forward/Reply Messages are followed by a relay message option, which is
followed by any dhcp message.

This changes relay message options to expect dhcp messages in their
payload.

Also, the _DHCP6GuessPayload.guess_payload_class() method was doing
some voodoo with ord() before which - at least in my case - just broke.

Also, this defines fields_desc in DHCP6_RelayReply anstead of (ab)using
DHCP6_RelayForward for this like it was before.

I'd like to do some more cleanup here, move things into separate files
etc, but first I'd like to fix things :-)

### CODE REVIEW

**Comment by phaethon** [comment]
Thanks for the commit. Please, add some test case case if you add new stuff.

**Comment by flokli** [comment]
@phaethon There is still something broken, as `DHCP6` has an `X3BytesField` in the `overload_fields` attribute. However, in case of `msgtype` `12` and `13` (`DHCP6_RelayForward`, `DHCP6_RelayReply`), the fields are different (and longer in total, which is why later packets get parsed wrongly). Is there any nice way to modify the `DHCP6` class itself to handle these `msgtypes` correctly, too?

**Comment by flokli** [comment]
Of course, I can parse the data via `DHCP6_RelayReply(data)` in this case, but IMHO, `DHCP6(data)` should work for all kind of `msgtype`.

**Comment by flokli** [comment]
@phaethon: Do you plan to do a release in the near future including this fix?

**Comment by phaethon** [comment]
All releases are based on the base code, so the fix will be included in the next release. I can do a minor release if you see it as important.

**Comment by phaethon** [comment]
Just did a minor release 0.19, which is now published on PiPy including this PR

**Comment by flokli** [comment]
Awesome, thanks!

**Pull request merged**
